name: Pipeline de Testes E2E - Blog do Agi

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1 - Clonar o Repositório
        uses: actions/checkout@v4

      - name: Passo 2 - Executar os Testes no Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run test:ci